const JOIN = 'JOIN'
const OUT_ROOM = 'OUT_ROOM'
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
const SEND_MESSAGE = 'SEND_MESSAGE'
const NEW_CONVERSATION = 'NEW_CONVERSATION'
const TYPING = 'TYPING'
const ISREAD = 'ISREAD'
const RECEIVED = 'RECEIVED'
const USER_ONLINE = 'USER_ONLINE'
module.exports = {
    JOIN,
    RECEIVE_MESSAGE,
    SEND_MESSAGE,
    OUT_ROOM,
    NEW_CONVERSATION,
    TYPING,
    ISREAD,
    RECEIVED,
    USER_ONLINE
}